language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements/install.txt
  - pip install -r requirements/testing.txt
# command to run tests
script: pytest --cov --flake8 --isort
